# Generated by Django 6.0.2 on 2026-02-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='allowed_branch',
        ),
        migrations.AddField(
            model_name='company',
            name='allowed_branches',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], default='CSE', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='drive_notice',
            field=models.FileField(blank=True, null=True, upload_to='drive_notices/'),
        ),
    ]
