# Generated by Django 6.0.2 on 2026-02-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_company_allowed_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='eligiblity_cgpa',
            new_name='eligibility_cgpa',
        ),
    ]
