# Generated by Django 6.0.2 on 2026-02-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='drive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
