# Generated by Django 6.0.2 on 2026-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
